### ISSUE TITLE
Using raw dicts instead of the Document class?

### ISSUE THREAD

**Issue by dekrypted** [VermiIIi0n/async-tinydb#18]
Hello!

I've recently switched over to this library. However, I've noticed it uses a new Document class instead of raw Json. This change is actually kind of cool, but I have a very large codebase and it would take a very long time to change everything over to this new system. Is there a way to use raw dicts like in the original tinydb?

I've tried setting document_class to dict, however this raises an exception when inserting new entries:
AttributeError: 'dict' object has no attribute 'doc_id'

Thanks!

**Comment by VermiIIi0n** [comment]
Hi dekrypted, thank you for liking this repo😁.

I have tried my best to maintain compatibility with the original TinyDB, you can insert a raw `dict` directly and it will be converted to your document class.

The modification you made is why this exception is raised, a document class requires this `doc_id` attribute, normally you wouldn't want to modify it.

**Comment by dekrypted** [comment]
Thank you for the help! For anyone who stumbles on this issue later, here's my resolution:

```py
from asynctinydb import BaseDocument
from typing import Dict, Any

class DictDocument(dict, BaseDocument):
    def __init__(self, value: Dict[str, Any], doc_id: Any):
        super().__init__(value)
        self._doc_id = doc_id

    @property
    def doc_id(self) -> Any:
        return self._doc_id

    @doc_id.setter
    def doc_id(self, value: Any):
        self._doc_id = value
```

And in any tables:
```
db.table("<table>", document_class=DictDocument)
```

**Comment by VermiIIi0n** [comment]
Glad you solved your issue. However, here is the definition of the default document class, and I don't see much of a difference. Could you explain the problem you encountered in detail?

```Python
class Document(dict, BaseDocument[IDVar]):
    """
    A document stored in the database.

    This class provides a way to access both a document's content and
    its ID using ``doc.doc_id``.
    """

    def __init__(self, value: Mapping, doc_id: IDVar):
        super().__init__(value)
        self.doc_id = doc_id

    @property
    def doc_id(self) -> IDVar:
        return self._doc_id

    @doc_id.setter
    def doc_id(self, value: IDVar):
        self._doc_id = value

    def __repr__(self):
        pp = json.dumps(self, indent=2, ensure_ascii=False, default=str)
        return f"Document(\n  doc_id={self.doc_id} \n  doc={pp})"
```

**Comment by dekrypted** [comment]
I'm actually not sure what the difference really is, but for some reason trying to initialize a class on the default base document as a dict wasn't working. However, after playing around the class I've sent above worked. I think this is just a case of Python being Python 🤷‍♂️
